name: Justfile CI

on:
  pull_request:
    paths:
      - "justfile"
  push:
    branches:
      - main
    paths:
      - "justfile"

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up just
        uses: taiki-e/install-action@481c34c1cf3a84c68b5e46f4eccfc82af798415a # v2.75.23
        with:
          tool: just@1.50.0
          fallback: none

      - name: Run formatter
        run: just --fmt --check
