name: Release Expert
on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release

  draft:
    name: draft
    needs: release
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - run: gh release edit ${{ needs.release.outputs.tag_name }} --draft=true --repo='elixir-lang/expert'

  build:
    needs: [release, draft]
    runs-on: macos-14
    if: ${{ needs.release.outputs.release_created }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: extractions/setup-just@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.3.4.1"
          elixir-version: "1.17.3"
          version-type: strict
      - uses: mlugg/setup-zig@v2
        with:
          version: "0.14.1"
      - uses: actions/checkout@v4
      - run: just release-all
        env:
          MIX_ENV: prod
      - name: Create Checksum
        run: |
          cd ./apps/expert/burrito_out
          chmod +x ./*
          shasum -a 256 ./* > expert_checksums.txt
          cd ../../../
      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: gh release upload ${{ needs.release.outputs.tag_name }} ./apps/expert/burrito_out/*

  publish:
    name: publish
    needs: [release, draft, build]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: gh release edit ${{ needs.release.outputs.tag_name }} --draft=false --repo='elixir-lang/expert'
